### ISSUE TITLE
a special unitary matrix have S matrix with imaginary part, 

### ISSUE THREAD

**Issue by desaisli** [ishdhand/Internal-Spatial-Decomposition#1]
I try to use this code to decompose the unitary matrix, but the S matrix have the imaginary part. Can this code only factorize special matrices?
here is the code and result：

clc
clear
m=2;n=2;

U=[
 0.740958, -0.565222 *1i, 0.362638, 0 ;
 -0.565222 *1i, 0.740958, 0, -0.362638;
 -0.362638, 0, 0.740958, -0.565222* 1i;
 0, 0.362638, -0.565222 *1i, 0.740958 ;
];

[L1,L2,R1,R2,S] = CSD(U,m,n);

![Snipaste_2024-03-10_11-14-27](https://github.com/ishdhand/Internal-Spatial-Decomposition/assets/53023783/213161a9-b93d-4a93-a640-b4eeb67ad998)

Thank you for your attention！

**Comment by ishdhand** [comment]
Thanks for your interest. I haven't looked at this code in almost a decade and also don't have the software to run it anymore. Terribly sorry but I won't be able to help you with this point.
